name: 💡 Feature request
description: Suggest an idea for this project
title: "[FEATURE REQUEST] your title here"
labels: ["bug: bug suspected"]
assignees:
  - AF-1

body:
- type: textarea
  attributes:
    label: Is your feature request related to a problem?
    description: A clear and concise description of what the problem is.
  validations:
    required: false
- type: markdown
  attributes:
    value: "<br><br>"
- type: textarea
  attributes:
    label: Describe the solution / feature you'd like
    description: A clear and concise description of what you want to happen
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br><br>"
- type: textarea
  attributes:
    label: "Describe alternatives you've considered"
    description: "A clear and concise description of any alternative solutions or features you've considered."
  validations:
    required: false
- type: markdown
  attributes:
    value: "<br><br>"
- type: input
  attributes:
    label: LMS version
    description: What version of LMS are you running?
    placeholder: "Example: 9.0.1"
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br>"
- type: input
  attributes:
    label: Plugin version
    description: What version of the plugin are you running?
    placeholder: "Example: 1.0.3"
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br><br>"
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Add any other context or **screenshots** about the feature request here.

      Tip: You can attach images (screenshots) or files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
