blank_issues_enabled: false
contact_links:
  - name: Lyrion Community Support Forum
    url: https://forums.lyrion.org/forum/user-forums/3rd-party-software/113984-announce-dynamic-playlists-4
    about: Please ask questions that are not related to bug reports or feature requests in the Lyrion Community Forum.
