blank_issues_enabled: false
contact_links:
  - name: Lyrion Community Forum Support
    url: https://forums.slimdevices.com/forum/user-forums/3rd-party-software/113984-announce-dynamic-playlists-4
    about: Please ask questions that are not related to bug reports or feature requests here.